import json
en_data = {
  "common": {
    "loading": "Loading...",
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "edit": "Edit",
    "search": "Search",
    "filter": "Filter",
    "export": "Export",
    "signOut": "Sign out",
    "logoutAll": "Logout from all devices",
    "settings": "Settings",
    "dashboard": "Dashboard",
    "payments": "Payments",
    "outages": "Outages",
    "config": "Config",
    "webhooks": "Webhooks",
    "bulkImport": "Bulk Import",
    "language": "Language",
    "tryAgain": "Try again",
    "reloadPage": "Reload page",
    "confirm": "Confirm",
    "close": "Close",
    "back": "Back",
    "next": "Next",
    "done": "Done",
    "skip": "Skip",
    "required": "Required",
    "optional": "Optional",
    "yes": "Yes",
    "no": "No",
    "create": "Create",
    "update": "Update",
    "remove": "Remove",
    "view": "View",
    "details": "Details",
    "status": "Status",
    "date": "Date",
    "amount": "Amount",
    "type": "Type",
    "actions": "Actions",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Info",
    "online": "Online",
    "offline": "Offline",
    "retry": "Retry",
    "reconciling": "Reconciling...",
    "retrying": "Retrying...",
    "confirmRetry": "Confirm Retry",
    "confirmReconcile": "Confirm Reconcile",
    "highValueWarning": "This payment of ${amount} exceeds the ${threshold} threshold. Please type \"CONFIRM\" to proceed with the {action}.",
    "copyCoordinates": "Copy coordinates",
    "copied": "Copied",
    "openInOpenStreetMap": "Open in OpenStreetMap",
    "mapUnavailable": "Map unavailable — coordinates provided below.",
    "mapDataCredit": "Map data © OpenStreetMap contributors",
    "loadingPayment": "Loading payment",
    "fetchingTransaction": "Fetching transaction metadata...",
    "failedToLoad": "Failed to load",
    "noLinkedOutage": "No linked outage",
    "paymentId": "Payment ID",
    "outage": "Outage",
    "from": "From",
    "to": "To",
    "transactionHash": "Transaction Hash",
    "created": "Created",
    "confirmed": "Confirmed",
    "asset": "Asset",
    "page": "Page",
    "of": "of",
    "total": "total",
    "previous": "Previous",
    "nextPage": "Next",
    "exportCSV": "Export CSV",
    "exporting": "Exporting...",
    "density": "Density",
    "default": "Default",
    "compact": "Compact",
    "statusFilter": "Status",
    "typeFilter": "Type",
    "dateFrom": "From",
    "dateTo": "To",
    "all": "All",
    "pending": "Pending",
    "completed": "Completed",
    "confirmedStatus": "Confirmed",
    "failed": "Failed",
    "reward": "Reward",
    "penalty": "Penalty",
    "standard": "Standard",
    "paymentDetails": "Payment Details",
    "closeDrawer": "Close drawer",
    "retryQueue": "Retry Queue",
    "systemHealth": "System Health",
    "mainnet": "MAINNET",
    "signIn": "Sign in",
    "logout": "Logout",
    "refreshSession": "Refresh session",
    "loadCreateAccount": "Load or create an operator account",
    "admin": "Admin",
    "updated": "Updated",
    "saving": "Saving...",
    "saveChanges": "Save Changes",
    "retrySucceeded": "Retry succeeded.",
    "reconcileSucceeded": "Reconciliation succeeded.",
    "retryFailed": "Retry failed. Please try again.",
    "reconcileFailed": "Reconciliation failed. Please try again.",
    "highValueActionTitle": "Confirm High-Value Action",
    "loadFailed": "Failed to load data. Please refresh.",
    "paymentsUnavailable": "Payments unavailable",
    "noPaymentsFound": "No payments found",
    "adjustFilters": "Try adjusting your filters.",
    "fetchingPayments": "Retrieving the latest reward and penalty records.",
    "loadingPayments": "Loading payments"
  },
  "navigation": {
    "home": "Home",
    "settings": "Settings",
    "systemHealth": "System Health"
  },
  "auth": {
    "login": "Login",
    "register": "Register",
    "email": "Email",
    "password": "Password",
    "signIn": "Sign in",
    "createAccount": "Create account"
  },
  "payments": {
    "title": "Payments",
    "amount": "Amount",
    "status": "Status",
    "date": "Date",
    "actions": "Actions",
    "viewDetails": "View Details"
  },
  "outages": {
    "title": "Outages",
    "newOutage": "New Outage",
    "resolve": "Resolve",
    "details": "Details",
    "status": "Status",
    "createdAt": "Created At",
    "updatedAt": "Updated At",
    "loadingOutages": "Loading outages",
    "gatheringIncidents": "Gathering the latest incident feed and table filters.",
    "loadingDetails": "Loading outage details",
    "pullingTimeline": "Pulling the incident timeline, SLA outcome, and payment state.",
    "outagesError": "Outages Error",
    "createOutageError": "Create Outage Error",
    "outageDetailsError": "Outage Details Error",
    "unexpectedError": "An unexpected error occurred while loading this page.",
    "searchOutages": "Search outages...",
    "newest": "Newest",
    "titleSort": "Title",
    "export": "Export",
    "selectAll": "Select all",
    "outagesSelected": "{count} outage(s) selected",
    "bulkAssign": "Bulk Assign",
    "bulkResolve": "Bulk Resolve",
    "bulkResolveTitle": "Bulk resolve outages",
    "bulkResolveConfirm": "Confirm to resolve {count} selected outage(s).",
    "bulkAssignTitle": "Bulk assign outages",
    "bulkAssignConfirm": "Assign {count} selected outage(s) to a team member.",
    "outagesToResolve": "Outages to resolve:",
    "outagesToAssign": "Outages to assign:",
    "mttrMinutes": "Mean time to resolve (minutes)",
    "mttrRequired": "MTTR is required.",
    "mttrInvalid": "MTTR must be a non-negative number.",
    "assignTo": "Assign to (user ID or name)",
    "assigneeRequired": "Please enter an assignee name or ID.",
    "confirmResolve": "Confirm Resolve",
    "confirmAssign": "Confirm Assign",
    "resolving": "Resolving...",
    "assigning": "Assigning...",
    "cancel": "Cancel",
    "deleteConfirm": "Delete outage?",
    "deleteConfirmMessage": "This will permanently delete outage {id} ({siteName}). This action cannot be undone.",
    "deleting": "Deleting...",
    "delete": "Delete",
    "retry": "Retry",
    "createOutage": "Create Outage",
    "backToOutages": "Back to outages",
    "siteName": "Site Name",
    "siteId": "Site ID",
    "severity": "Severity",
    "outageStatus": "Status",
    "detectedAt": "Detected At",
    "description": "Description",
    "affectedServices": "Affected Services",
    "affectedSubscribers": "Affected Subscribers",
    "assignedTo": "Assigned To",
    "siteNamePlaceholder": "e.g. Lagos Node 1",
    "siteIdPlaceholder": "Optional",
    "descriptionPlaceholder": "Describe the outage…",
    "affectedServicesPlaceholder": "Comma-separated, e.g. DNS, VoIP",
    "affectedSubscribersPlaceholder": "Optional",
    "assignedToPlaceholder": "Optional",
    "creating": "Creating…",
    "siteNameRequired": "Site name and description are required.",
    "editOutage": "Edit Outage",
    "edit": "Edit",
    "resolveOutage": "Resolve Outage",
    "outageResolved": "Outage Resolved",
    "metadata": "Metadata",
    "timeline": "Timeline",
    "slaResult": "SLA Result",
    "resolutionPayment": "Resolution Payment",
    "impact": "Impact",
    "outageHistory": "Outage History",
    "location": "Location",
    "postIncidentAnalysis": "Post-Incident Analysis",
    "rootCause": "Root Cause",
    "resolutionNotes": "Resolution Notes",
    "affectedServicesList": "Affected Services",
    "subscribers": "Subscribers",
    "startedAt": "Started At",
    "resolvedAt": "Resolved At",
    "ongoing": "Ongoing",
    "slaStatus": "Status",
    "slaRating": "Rating",
    "slaAmount": "Amount",
    "noSlaComputed": "No SLA computed yet.",
    "paymentStatus": "Status",
    "paymentAmount": "Amount",
    "paymentFrom": "From",
    "paymentTo": "To",
    "paymentTransaction": "Transaction",
    "resolveToViewPayment": "Resolve the outage to view the generated payment record.",
    "noHistoryEvents": "No history events available yet.",
    "noLocationData": "No location data available for this outage.",
    "noRootCa
