blank_issues_enabled: true
contact_links:
  - name: ApexChain Documentation
    url: https://github.com/ApexChainx/ApexChainx-Frontend/tree/main/docs
    about: Check the documentation before filing an issue
  - name: ApexChain Discussions
    url: https://github.com/ApexChainx/ApexChainx-Frontend/discussions
    about: Ask questions and discuss ideas here
